title:              Syghtware
email:              syghtware@gmail.com
description:        Los puntos de vista son tecnolog√≠as.
author:             Juan Zaragoza
baseurl:            ""
url:                "https://juanfernandezzaragoza.github.io/syghtware/"

# Social Profiles
twitter_username:   syghtware
instagram_username: syghtware 
linkedin_page: syghtware
youtube_channel: UCC2KcYxcngo9n6lwxvOwMEw

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-6D4L138TWT # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
